### ISSUE TITLE
Army info popup in crusade mode

### ISSUE THREAD

**Issue by veidral** [factubsio/BubbleTweaks#5]
**Describe the bug**
With bubble tweaks installed you can´t see the army information popup in crusade mode. 

**To Reproduce**
1. Go to crusade mode
2. Click on the i button when selecting one of your own armies.
3. Nothing happens. 

**Expected behavior**
The information screen for the army would appear. 

**Additional context**
When the mod is disabled, the army popup works.

**Comment by factubsio** [comment]
Should be fixed now (and the disband button too), sorry, I managed to miss some icon pngs which then broke something. bad bubbles 😔
