### ISSUE TITLE
Please add documentation for the "AOE indicators" feature

### ISSUE THREAD

**Issue by mronnblom** [factubsio/BubbleTweaks#6]
Some brief explanation in the readme should be enough, together with:
* Which are the available "types" to enter and what effect do they have
* Which values in `aoe_indicators.json` are changed from their vanilla default

Thanks!

**Comment by factubsio** [comment]
Not entirely sure what you mean by "vanilla" normals?

For type you can have:
 * `good` - uses colors from `__default_good__` at the very bottom of the file
 * `bad` - uses colors from `__default_bad__` at the very bottom of the file
 * `skip` - no circle

You can also supply either (or both) of the normal/hi colors directly as rgb:
```
    {
      //EXAMPLE_DOES_NOT_EXIST: use "hi" and "normal" to set custom rgb for the highlighted/normal circles
      "ability": "EXAMPLE",
      "hi": [ 1, 1, 1 ],
      "normal": [ 0.4, 0.3, 0.2 ]
    },
```

`normal` - normal color of circle
`hi` - color of circle when you path over it in TBM

**Comment by factubsio** [comment]
Added this to the README.md too

**Comment by mronnblom-cint** [comment]
What I meant was that it would be nice to know which circles/colors are changed from how the game normally (without this mod) displays. But maybe I have misunderstood this function..

**Comment by factubsio** [comment]
The game does not display circles so it's almost impossible to see exactly where the edge of e.g. a grease or pit area ends. The mod adds the circles.

**Comment by mronnblom-cint** [comment]
Ahaaa, it's for spells already cast, not when casting them. Got it!

**Comment by factubsio** [comment]
👍
