### ISSUE TITLE
 The game will get stuck with infinite load 

### ISSUE THREAD

**Issue by highfly117** [factubsio/BubbleTweaks#7]
**Describe the bug**
Once the mod is installed with unity mod manager 0.23.0 the game when trying to load a save or finish the Character creation the game will be super slow to load and will never load once it reaches 100%

**To Reproduce**
install game
install unity mod manager
install bubble tweaks
load save or finish character creation 

**Expected behavior**
Game to load and mod to work

**Comment by factubsio** [comment]
What version? What other mods?

**Comment by highfly117** [comment]
1.2.0af and 1.2.0aa

**Comment by factubsio** [comment]
No other mods? Can you attach your Player.log to the issue please.

**Comment by highfly117** [comment]
No other mods no

**Comment by highfly117** [comment]
Mono path[0] = 'F:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/Managed'
Mono config path = 'F:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.26f1 (e0392c6b2363)
[Subsystems] Discovering subsystems at path F:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   
    VRAM:     8079 MB
    Driver:   30.0.15.1179
Begin MonoManager ReloadAssembly
- Completed reload, in  0.129 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.661000 ms


[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.24.2.0.
[Manager] OS: Microsoft Windows NT 10.0.19044.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.261.
[Manager] Game: Pathfinder: Wrath of the Righteous.
[Manager] Mods path: F:\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Mods.
Fallback handler could not load library F:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/Mono/data-0000019153E86660.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/Mono/data-00000191CA249180.dll
[Manager] Injection successful.
[Manager] Start parsing game version.
[Manager] Found game version string: '1.2.0af'.
[Manager] Game version detected as '1.2.0'.
[Manager] Parsing mods.
[Manager] Reading file 'F:\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Mods\BubbleTweaks\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[BubbleTweaks] Version '1.13.0'. Loading.
[BubbleTweaks] HELLO???
[BubbleTweaks] Loaded bundle
[BubbleTweaks] Found ldc 1 @ 11
[BubbleTweaks] Found ldc 1 @ 10
[BubbleTweaks] Found ldc 1 @ 7
[BubbleTweaks] SpeedTweakController initialized
[BubbleTweaks] --INSTALLING CRUSADE TWEAKS--
[BubbleTweaks] Active.
[BubbleTweaks] Loading time 0.21 s.
[Manager] FINISH. SUCCESSFUL LOADED 1/1 MODS.


[Manager] Spawning.
[MonoSingleton] There is no object of type Kingmaker.Settings.Graphics.ApplicationFocusObserver. Creating new.
[MonoSingleton] There is no object of type Kingmaker.Utility.CoroutineRunner. Creating new.
Cannot Prepare a disabled VideoPlayer 
(Filename:  Line: 315)

[Manager] Checking updates.
The referenced script on this Behaviour (Game Object 'Male_BaseSkeletonGeneric_HalfOrc') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

[BubbleTweaks] dropdown null: False
Setting up 4 worker threads for Enlighten.
  Thread -> id: 2de8 -> priority: 1 
  Thread -> id: 4360 -> priority: 1 
  Thread -> id: 2dfc -> priority: 1 
  Thread -> id: f28 -> priority: 1 
[BubbleTweaks] SpeedTweakController destroyed
[Manager] Destroying when exit.

**Comment by factubsio** [comment]
This is very spooky. I'll try to go through char creation today but can you send me the save in the meantime? 😔

**Comment by highfly117** [comment]
sorry i don't have any save files anymore with re-installing they have gone

**Comment by factubsio** [comment]
What version of the mod? 🤔

**Comment by factubsio** [comment]
BubbleTweaks should not touch the scene persistance at all,

**Comment by highfly117** [comment]
whatever the issue was it has been fixed in version 1.14 I can play the game fine with the later version Thanks
